Wolnosciowiec\FileRepositoryBundle\Model\Entity\CachedResource:
    type: entity
    table: fr_bundle_cached_resource
    repositoryClass: Wolnosciowiec\FileRepositoryBundle\Model\Repository\CachedResourceRepository

    id:
        id:
            type: guid
            nullable: false
            id: true
            length: 36
            generator:
                strategy: UUID

    fields:
        url:
            type: string
            length: 128
            unique: true
            nullable: false
        active:
            type: boolean
            options:
                default: 0