services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # a wrapper class that injects dependencies
    Wolnosciowiec\FileRepositoryBundle\Service\Http\Client:
        class: Wolnosciowiec\FileRepositoryBundle\Service\Http\Client
        public: true

    wolnosciowiec.file_repository.registry:
        class: Wolnosciowiec\FileRepositoryBundle\Service\FileRegistry
        public: true
        arguments:
            $client: '@Wolnosciowiec\FileRepositoryBundle\Service\Http\Client'

    wolnosciowiec.file_repository.uploader:
        class: Wolnosciowiec\FileRepositoryBundle\Service\FileUploader
        public: true
        arguments:
            $client: '@Wolnosciowiec\FileRepositoryBundle\Service\Http\Client'
            
    wolnosciowiec.file_repository.token_manager:
        class: Wolnosciowiec\FileRepositoryBundle\Service\TokenManager
        public: true
        arguments:
            $client: '@Wolnosciowiec\FileRepositoryBundle\Service\Http\Client'

    wolnosciowiec.file_repository.user_upload_manager:
        class: Wolnosciowiec\FileRepositoryBundle\Service\UserUploadManager
        public: true
        arguments:
            $client: '@Wolnosciowiec\FileRepositoryBundle\Service\Http\Client'
