services:
    # a wrapper class that injects dependencies
    wolnosciowiec.file_repository.client:
        class: Wolnosciowiec\FileRepositoryBundle\Service\Http\Client

    wolnosciowiec.file_repository.registry:
        class: Wolnosciowiec\FileRepositoryBundle\Service\FileRegistry
        arguments:
            client: "@wolnosciowiec.file_repository.client"
            serializer: "@serializer"

    wolnosciowiec.file_repository.uploader:
        class: Wolnosciowiec\FileRepositoryBundle\Service\FileUploader
        arguments:
            client: "@wolnosciowiec.file_repository.client"
            
    wolnosciowiec.file_repository.token_manager:
        class: Wolnosciowiec\FileRepositoryBundle\Service\TokenManager
        arguments:
            client: "@wolnosciowiec.file_repository.client"

    wolnosciowiec.file_repository.user_upload_manager:
        class: Wolnosciowiec\FileRepositoryBundle\Service\UserUploadManager
        arguments:
            client: "@wolnosciowiec.file_repository.client"

    # repository of local cached resources
    wolnosciowiec.file_repository.repository.cached_resource:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Wolnosciowiec\FileRepositoryBundle\Model\Entity\CachedResource

    # registry for cached resources
    wolnosciowiec.file_repository.local_resource_registry:
        class: Wolnosciowiec\FileRepositoryBundle\Service\Manager\LocalResourceRegistry
        arguments:
            repository: "@wolnosciowiec.file_repository.repository.cached_resource"

    # serializes cached resources into data understandable by
    wolnosciowiec.file_repository.serializer.rmv:
        class: Wolnosciowiec\FileRepositoryBundle\Service\RMVSerializer