language: php
php:
  - '7.0'
  - nightly

before_script:
  - composer install
  - composer dump-autoload -o
  - composer require satooshi/php-coveralls:dev-master

script: ./bin/phpunit.sh --coverage-clover clover.xml

after_success:
  - php vendor/bin/coveralls -v --coverage_clover clover.xml