language: php
php:
  - '7.0'
  - nightly

before_script:
  - composer install
  - composer dump-autoload -o
  - composer require satooshi/php-coveralls:dev-master
  - mkdir ./tests/logs

script: ./bin/phpunit.sh --coverage-clover ./tests/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v